import {describe,it,expect} from 'vitest';
import {commercialMetrics,type Row} from '../../../supabase/functions/instagram-commercial/model';
const base=()=>({campaigns:[{id:'a'},{id:'b'}],recipients:[{id:'1',campaign_id:'a',lead_id:'lead',replied_at:'2026-09-01'}],conversations:[] as Row[],leads:[{id:'lead',bant_need:true}],events:[] as Row[],deals:[] as Row[],intermediations:[] as Row[]});
describe('commercial attribution',()=>{
 it('attributes one person only to first responding campaign',()=>{const x=base();x.recipients.push({id:'2',campaign_id:'b',lead_id:'lead',replied_at:'2026-09-02'});const r=commercialMetrics(x);expect(r.total.conversations).toBe(1);expect(r.byCampaign.a.qualified).toBe(1);expect(r.byCampaign.b.conversations).toBe(0)});
 it('counts people not multiple deals and excludes earlier wins',()=>{const x=base();x.deals=[{lead_id:'lead',status:'won',won_at:'2026-09-02'},{lead_id:'lead',status:'won',won_at:'2026-09-03'}];expect(commercialMetrics(x).total.sales).toBe(1);x.deals=[{lead_id:'lead',status:'won',won_at:'2026-08-01'}];expect(commercialMetrics(x).total.sales).toBe(0)});
 it('requires signed contracts and excludes cancelled appointments',()=>{const x=base();x.events=[{lead_id:'lead',status:'cancelled',created_at:'2026-09-02',start_datetime:'2026-09-03'}];x.intermediations=[{owner_lead_id:'lead',status:'active',contract_status:'draft',contract_signed_at:'2026-09-02'}];let r=commercialMetrics(x);expect(r.total.captures).toBe(0);expect(r.total.appointments).toBe(0);x.intermediations[0].contract_status='signed';expect(commercialMetrics(x).total.captures).toBe(1)});
 it('does not infer a lead from ambiguous identity or invent qualification',()=>{const x=base();x.recipients=[{id:'1',campaign_id:'a',lead_id:'missing',replied_at:'2026-09-01'}];const r=commercialMetrics(x);expect(r.total.unlinked).toBe(1);expect(r.total.qualified).toBe(0)});
 it('resolves an exact conversation identity when there is one lead',()=>{const x=base();x.recipients=[{id:'1',campaign_id:'a',lead_id:'',replied_at:'2026-09-01',recipient_psid:'psid'} as typeof x.recipients[0]];x.conversations=[{participant_instagram_id:'psid',lead_id:'lead'}];expect(commercialMetrics(x).total.conversations).toBe(1)});
});
